server:
    port: 80
    tomcat:
    uri-encoding: utf-8
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/webspider
        username: admin
        password: admin
    jpa:
        database: MYSQL
        show-sql: false
        #Hibernate ddl auto (validate|create|create-drop|update)
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    redis:
        host: 127.0.0.1
        port: 6739
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1
    thymeleaf:
        prefix: classpath:html
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        content-type: text/html
        cache: false
        